---
pkcs7_private_key: '/etc/puppetlabs/puppet/environments/production/secure/keys/private_key.pkcs7.pem'
pkcs7_public_key: '/etc/puppetlabs/puppet/environments/production/secure/keys/public_key.pkcs7.pem'
